/* license-management-core test suite.
 *
 * Pure-C unit tests plus vector-driven compatibility tests. The vectors are
 * generated by tools/vectorgen (a .NET program that reuses the SAME signing
 * code path as the license server), so a green run here proves the C core
 * verifies what the real .NET server signs — RS256 and ES256 — and rejects
 * tampered tokens. On Windows every vector also runs against the CNG backend,
 * cross-checking the portable RSA/P-256 implementations against the OS crypto.
 *
 * Multiple vector files may be passed (vectors.json vectors-eddsa.json ...);
 * each contributes whichever of RsaJwk/EcJwk/EdJwk and test sections it has.
 * The EdDSA file comes from tools/eddsa-vectorgen (signed with a fixed
 * Ed25519 key by the `cryptography` reference implementation).
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "hymma/hlm.h"
#include "hlm_sha256.h"
#include "hlm_sha512.h"
#include "hlm_b64url.h"
#include "hlm_json.h"

static int failures;
static int checks;

#define CHECK(cond, name)                                                    \
    do {                                                                     \
        checks++;                                                            \
        if (!(cond)) {                                                       \
            failures++;                                                      \
            printf("FAIL %s (%s:%d)\n", name, __FILE__, __LINE__);           \
        }                                                                    \
    } while (0)

static void hex(const uint8_t *in, size_t len, char *out)
{
    static const char H[] = "0123456789abcdef";
    size_t i;
    for (i = 0; i < len; i++) {
        out[i * 2] = H[in[i] >> 4];
        out[i * 2 + 1] = H[in[i] & 0xf];
    }
    out[len * 2] = '\0';
}

/* ------------------------------------------------------------------ */

static void test_sha256(void)
{
    uint8_t d[32];
    char h[65];

    hlm_sha256("abc", 3, d);
    hex(d, 32, h);
    CHECK(strcmp(h, "ba7816bf8f01cfea414140de5dae2223"
                    "b00361a396177a9cb410ff61f20015ad") == 0,
          "sha256(abc)");

    hlm_sha256("", 0, d);
    hex(d, 32, h);
    CHECK(strcmp(h, "e3b0c44298fc1c149afbf4c8996fb924"
                    "27ae41e4649b934ca495991b7852b855") == 0,
          "sha256(empty)");
}

static void test_b64url(void)
{
    uint8_t buf[64];
    char enc[128];
    size_t n;

    n = hlm_b64url_decode("aGVsbG8", 7, buf, sizeof(buf));
    CHECK(n == 5 && memcmp(buf, "hello", 5) == 0, "b64url decode hello");

    n = hlm_b64url_encode((const uint8_t *)"hello", 5, enc, sizeof(enc));
    CHECK(n == 7 && strcmp(enc, "aGVsbG8") == 0, "b64url encode hello");

    /* round-trip all byte values */
    {
        uint8_t all[256];
        uint8_t back[256];
        char mid[400];
        int i;
        for (i = 0; i < 256; i++) all[i] = (uint8_t)i;
        n = hlm_b64url_encode(all, 256, mid, sizeof(mid));
        CHECK(n != (size_t)-1, "b64url encode 256");
        n = hlm_b64url_decode(mid, n, back, sizeof(back));
        CHECK(n == 256 && memcmp(all, back, 256) == 0, "b64url roundtrip");
    }

    CHECK(hlm_b64url_decode("a===", 4, buf, sizeof(buf)) == (size_t)-1,
          "b64url reject 4k+1");
    CHECK(hlm_b64url_decode("a$b", 3, buf, sizeof(buf)) == (size_t)-1,
          "b64url reject bad char");
}

static void test_json(void)
{
    static const char SRC[] =
        "{\"Id\":\"LIC_1\",\"Qty\":10,\"Ok\":true,\"None\":null,"
        "\"Nested\":{\"Name\":\"a \\\"b\\\" \\u00e9\"},"
        "\"Arr\":[{\"Key\":\"k1\"},{\"Key\":\"k2\"}]}";
    hlm_json_tok toks[64];
    hlm_json_doc doc;
    int n = hlm_json_parse(SRC, sizeof(SRC) - 1, toks, 64);
    int t;
    char s[64];
    int64_t v;
    int b;

    CHECK(n > 0, "json parse ok");
    hlm_json_doc_init(&doc, SRC, sizeof(SRC) - 1, toks, n);

    t = hlm_json_member(&doc, 0, "Id");
    CHECK(t >= 0 && hlm_json_string(&doc, t, s, sizeof(s)) == 5 &&
              strcmp(s, "LIC_1") == 0,
          "json string member");

    t = hlm_json_member(&doc, 0, "Qty");
    CHECK(t >= 0 && hlm_json_int64(&doc, t, &v) == 0 && v == 10, "json int");

    t = hlm_json_member(&doc, 0, "Ok");
    CHECK(t >= 0 && hlm_json_bool(&doc, t, &b) == 0 && b == 1, "json bool");

    t = hlm_json_member(&doc, 0, "None");
    CHECK(t >= 0 && hlm_json_is_null(&doc, t), "json null");

    t = hlm_json_member(&doc, 0, "Nested");
    CHECK(t >= 0, "json nested obj");
    t = hlm_json_member(&doc, t, "Name");
    CHECK(t >= 0 && hlm_json_string(&doc, t, s, sizeof(s)) != (size_t)-1 &&
              strcmp(s, "a \"b\" \xc3\xa9") == 0,
          "json escapes");

    t = hlm_json_member(&doc, 0, "Arr");
    CHECK(t >= 0, "json array member");
    {
        int e0 = hlm_json_element(&doc, t, 0);
        int e1 = hlm_json_element(&doc, t, 1);
        int e2 = hlm_json_element(&doc, t, 2);
        CHECK(e0 >= 0 && e1 >= 0 && e2 < 0, "json array elements");
        t = hlm_json_member(&doc, e1, "Key");
        CHECK(t >= 0 && hlm_json_string(&doc, t, s, sizeof(s)) == 2 &&
                  strcmp(s, "k2") == 0,
              "json array nested");
    }
}

static void test_iso8601(void)
{
    int64_t v;

    CHECK(hlm_parse_iso8601("1970-01-01T00:00:00Z", 20, &v) == 0 && v == 0,
          "iso epoch");
    CHECK(hlm_parse_iso8601("2026-07-10T00:00:00Z", 20, &v) == 0 &&
              v == 1783641600LL,
          "iso 2026-07-10");
    CHECK(hlm_parse_iso8601("2026-07-20T13:44:38.2833333", 27, &v) == 0 &&
              v == 1784555078LL,
          "iso fractional no offset");
    CHECK(hlm_parse_iso8601("2026-07-10T02:00:00+02:00", 25, &v) == 0 &&
              v == 1783641600LL,
          "iso positive offset");
    CHECK(hlm_parse_iso8601("garbage", 7, &v) != 0, "iso reject garbage");
}

static void test_status_engine(void)
{
    hlm_license lic;
    memset(&lic, 0, sizeof(lic));
    lic.expires = 2000;
    lic.trial_end = HLM_TIME_NONE;
    lic.first_paid_on = HLM_TIME_NONE;
    lic.created = HLM_TIME_NONE;
    lic.updated = HLM_TIME_NONE;
    lic.receipt.expires = HLM_TIME_NONE;

    /* file expiry always wins */
    lic.server_status = HLM_STATUS_VALID;
    CHECK(hlm_license_status(&lic, 2000) == HLM_STATUS_EXPIRED,
          "status: file expiry beats server status");
    CHECK(hlm_license_status(&lic, 1999) == HLM_STATUS_VALID,
          "status: server status trusted before expiry");

    /* legacy fallback: trial */
    lic.server_status = HLM_STATUS_UNKNOWN;
    lic.trial_end = 1500;
    CHECK(hlm_license_status(&lic, 1000) == HLM_STATUS_VALID_TRIAL,
          "status: legacy valid trial");
    CHECK(hlm_license_status(&lic, 1600) == HLM_STATUS_INVALID_TRIAL,
          "status: legacy invalid trial");

    /* legacy fallback: paid */
    lic.updated = 100;
    lic.has_receipt = 0;
    CHECK(hlm_license_status(&lic, 1000) == HLM_STATUS_RECEIPT_UNREGISTERED,
          "status: legacy unregistered");
    lic.has_receipt = 1;
    lic.receipt.expires = 900;
    CHECK(hlm_license_status(&lic, 1000) == HLM_STATUS_RECEIPT_EXPIRED,
          "status: legacy receipt expired");
    lic.receipt.expires = 1900;
    CHECK(hlm_license_status(&lic, 1000) == HLM_STATUS_VALID,
          "status: legacy valid");
}

static size_t unhex(const char *s, uint8_t *out)
{
    size_t i, n = strlen(s) / 2;
    for (i = 0; i < n; i++) {
        unsigned v;
        sscanf(s + 2 * i, "%2x", &v);
        out[i] = (uint8_t)v;
    }
    return n;
}

static void test_sha512(void)
{
    uint8_t d[64];
    char h[129];

    hlm_sha512("abc", 3, d);
    hex(d, 64, h);
    CHECK(strcmp(h, "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a"
                    "2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f") == 0,
          "sha512(abc)");

    hlm_sha512("", 0, d);
    hex(d, 64, h);
    CHECK(strcmp(h, "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce"
                    "47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e") == 0,
          "sha512(empty)");

    /* block boundary: 128 * 'a' */
    {
        char a[128];
        memset(a, 'a', sizeof(a));
        hlm_sha512(a, sizeof(a), d);
        hex(d, 64, h);
        CHECK(strcmp(h, "b73d1929aa615934e61a871596b3f3b33359f42b8175602e89f7e06e5f658a24"
                        "3667807ed300314b95cacdd579f3e33abdfbe351909519a846d465c59582f321") == 0,
              "sha512(128*a)");
    }
}

/* Raw Ed25519 vectors generated by the `cryptography` reference
 * implementation (see tools/eddsa-vectorgen) — the empty message and one
 * crossing no block boundary. The JWS-level EdDSA coverage comes from the
 * vectors-eddsa.json file. */
static void test_ed25519_raw(void)
{
    hlm_crypto crypto = hlm_crypto_portable();
    hlm_public_key key;
    uint8_t pub[32], msg[128], sig[64];
    size_t msg_len;

    key.alg = HLM_ALG_EDDSA;
    key.u.ed25519.pub = pub;

    unhex("d1a0a3f2306652e0629f48b49564b13dc21ec3b38dccb9b5651631cb6811b9f0", pub);
    unhex("a375361753b01a51060693c54a8e444082bb536a9420c76e3477c2f873abfdec"
          "565a778e6e1056b9f1d8a7f5e45e558ded088f19e7ef714bfe2ddc61bae9060b", sig);
    CHECK(crypto.verify(crypto.user, &key, msg, 0, sig, 64) == 1,
          "ed25519 empty message");
    sig[0] ^= 1;
    CHECK(crypto.verify(crypto.user, &key, msg, 0, sig, 64) == 0,
          "ed25519 tampered R rejected");

    unhex("7130539633c2f5ac95e8a728570dc06eee7f165f85098a93a9f9d66a08b4e44b", pub);
    msg_len = unhex("96", msg);
    unhex("b415e9b5707566a56020b4a47771e744bec43eb1333f8d7ecbca9c94be651e19"
          "b9e8df106a7d43d5f4c3ddf8e562391819b2f31ed6cd0ebc02d4725b000af301", sig);
    CHECK(crypto.verify(crypto.user, &key, msg, msg_len, sig, 64) == 1,
          "ed25519 one-byte message");
    msg[0] ^= 1;
    CHECK(crypto.verify(crypto.user, &key, msg, msg_len, sig, 64) == 0,
          "ed25519 tampered message rejected");
    CHECK(crypto.verify(crypto.user, &key, msg, msg_len, sig, 63) == 0,
          "ed25519 wrong signature length rejected");
}

/* ------------------------------------------------------------------ */
/* vector-driven                                                       */
/* ------------------------------------------------------------------ */

static char vec_src[131072];
static hlm_json_tok vec_toks[4096];
static hlm_json_doc vec;

static uint8_t rsa_keybuf[1024];
static uint8_t ec_keybuf[128];
static uint8_t ed_keybuf[64];
static hlm_public_key keys[3];
static size_t key_count;

static int load_vectors(const char *path)
{
    FILE *f = fopen(path, "rb");
    size_t n;
    int ntok;

    if (f == NULL) {
        printf("cannot open vectors file: %s\n", path);
        return -1;
    }
    n = fread(vec_src, 1, sizeof(vec_src) - 1, f);
    fclose(f);
    vec_src[n] = '\0';

    ntok = hlm_json_parse(vec_src, n, vec_toks, 4096);
    if (ntok <= 0) {
        printf("vectors file did not parse: %d\n", ntok);
        return -1;
    }
    hlm_json_doc_init(&vec, vec_src, n, vec_toks, ntok);
    return 0;
}

/* Parse whichever of RsaJwk / EcJwk / EdJwk this vector file carries. */
static void test_vector_keys(void)
{
    static const struct {
        const char *member;
        uint8_t *buf;
        size_t buf_len;
        const char *label;
    } JWKS[] = {
        { "RsaJwk", rsa_keybuf, sizeof(rsa_keybuf), "parse RSA JWK" },
        { "EcJwk", ec_keybuf, sizeof(ec_keybuf), "parse EC JWK" },
        { "EdJwk", ed_keybuf, sizeof(ed_keybuf), "parse Ed25519 JWK" },
    };
    size_t i;

    key_count = 0;
    for (i = 0; i < sizeof(JWKS) / sizeof(JWKS[0]); i++) {
        int t = hlm_json_member(&vec, 0, JWKS[i].member);
        const char *raw;
        size_t raw_len;

        if (t < 0) continue;
        raw = vec.src + vec.toks[t].start;
        raw_len = (size_t)(vec.toks[t].end - vec.toks[t].start);
        CHECK(hlm_jwk_parse(raw, raw_len, &keys[key_count], JWKS[i].buf,
                            JWKS[i].buf_len) == HLM_OK,
              JWKS[i].label);
        key_count++;
    }
    CHECK(key_count > 0, "vector file carries at least one JWK");
}

static void test_vector_sha256(void)
{
    int arr = hlm_json_member(&vec, 0, "Sha256");
    int i;

    if (arr < 0) return;
    for (i = 0;; i++) {
        int el = hlm_json_element(&vec, arr, i);
        char input[512], expected[80], got[65];
        uint8_t d[32];
        int t;
        size_t n, n2;

        if (el < 0) break;
        t = hlm_json_member(&vec, el, "Input");
        n = hlm_json_string(&vec, t, input, sizeof(input));
        CHECK(n != (size_t)-1, "sha256 vector input decodes");
        if (n == (size_t)-1) continue;
        t = hlm_json_member(&vec, el, "Hex");
        n2 = hlm_json_string(&vec, t, expected, sizeof(expected));
        CHECK(n2 != (size_t)-1, "sha256 vector hex decodes");
        if (n2 == (size_t)-1) continue;

        hlm_sha256(input, n, d);
        hex(d, 32, got);
        CHECK(strcmp(got, expected) == 0, "sha256 vector");
    }
}

static void test_vector_fingerprint(void)
{
    int arr = hlm_json_member(&vec, 0, "Fingerprint");
    int i;

    if (arr < 0) return;
    for (i = 0;; i++) {
        int el = hlm_json_element(&vec, arr, i);
        char c1[128], c2[128], expected[64], got[64];
        const char *components[2];
        int t, comps, ok;

        if (el < 0) break;
        comps = hlm_json_member(&vec, el, "Components");
        t = hlm_json_element(&vec, comps, 0);
        ok = hlm_json_string(&vec, t, c1, sizeof(c1)) != (size_t)-1;
        t = hlm_json_element(&vec, comps, 1);
        if (t >= 0)
            ok = ok && hlm_json_string(&vec, t, c2, sizeof(c2)) != (size_t)-1;
        t = hlm_json_member(&vec, el, "Expected");
        ok = ok && hlm_json_string(&vec, t, expected, sizeof(expected)) !=
                       (size_t)-1;
        CHECK(ok, "fingerprint vector fields decode");
        if (!ok) continue;

        components[0] = c1;
        components[1] = c2;
        CHECK(hlm_fingerprint(components,
                              hlm_json_element(&vec, comps, 1) >= 0 ? 2 : 1,
                              got, sizeof(got)) == HLM_OK &&
                  strcmp(got, expected) == 0,
              "fingerprint vector");
    }
}

static void run_case(int el, const hlm_crypto *crypto, const char *backend)
{
    static char jws[65536];
    char name[64], status_name[32], lic_id[64], now_str[40];
    int t, valid = 1;
    int64_t now = 0;
    hlm_license lic;
    hlm_status status;
    int r;
    char label[160];

    t = hlm_json_member(&vec, el, "Name");
    hlm_json_string(&vec, t, name, sizeof(name));

    t = hlm_json_member(&vec, el, "Jws");
    if (hlm_json_string(&vec, t, jws, sizeof(jws)) == (size_t)-1) {
        CHECK(0, "case jws too large");
        return;
    }

    t = hlm_json_member(&vec, el, "Valid");
    if (t >= 0) hlm_json_bool(&vec, t, &valid);

    t = hlm_json_member(&vec, el, "NowUtc");
    if (t >= 0 && hlm_json_string(&vec, t, now_str, sizeof(now_str)) != (size_t)-1)
        hlm_parse_iso8601(now_str, strlen(now_str), &now);

    r = hlm_license_check(jws, strlen(jws), keys, key_count, crypto,
                          NULL, NULL, now, &lic, &status);

    snprintf(label, sizeof(label), "case %s [%s]", name, backend);
    if (valid) {
        CHECK(r == HLM_OK, label);
        if (r != HLM_OK) {
            printf("  -> %s\n", hlm_err_str(r));
            return;
        }
        t = hlm_json_member(&vec, el, "ExpectedStatus");
        if (t >= 0 &&
            hlm_json_string(&vec, t, status_name, sizeof(status_name)) !=
                (size_t)-1) {
            snprintf(label, sizeof(label), "case %s status [%s]", name, backend);
            CHECK(strcmp(hlm_status_str(status), status_name) == 0, label);
            if (strcmp(hlm_status_str(status), status_name) != 0)
                printf("  -> got %s want %s\n", hlm_status_str(status),
                       status_name);
        }
        t = hlm_json_member(&vec, el, "LicenseId");
        if (t >= 0 &&
            hlm_json_string(&vec, t, lic_id, sizeof(lic_id)) != (size_t)-1) {
            snprintf(label, sizeof(label), "case %s licid [%s]", name, backend);
            CHECK(strcmp(lic.id, lic_id) == 0, label);
        }
    } else {
        snprintf(label, sizeof(label), "case %s rejected [%s]", name, backend);
        CHECK(r == HLM_E_SIGNATURE || r == HLM_E_FORMAT, label);
        if (!(r == HLM_E_SIGNATURE || r == HLM_E_FORMAT))
            printf("  -> unexpectedly %s\n", hlm_err_str(r));
    }
}

static void test_vector_cases(void)
{
    int arr = hlm_json_member(&vec, 0, "Cases");
    int i;
    hlm_crypto portable = hlm_crypto_portable();
#if defined(_WIN32)
    hlm_crypto cng = hlm_crypto_cng();
#endif

    CHECK(arr >= 0, "vectors Cases present");
    for (i = 0;; i++) {
        int el = hlm_json_element(&vec, arr, i);
        if (el < 0) break;
        run_case(el, &portable, "portable");
#if defined(_WIN32)
        run_case(el, &cng, "cng");
#endif
    }
}

int main(int argc, char **argv)
{
    int a;

    test_sha256();
    test_sha512();
    test_b64url();
    test_json();
    test_iso8601();
    test_status_engine();
    test_ed25519_raw();

    for (a = 1; a < argc; a++) {
        if (load_vectors(argv[a]) == 0) {
            test_vector_keys();
            test_vector_sha256();
            test_vector_fingerprint();
            test_vector_cases();
        } else {
            failures++;
        }
    }
    if (argc <= 1)
        printf("note: no vectors file given — ran unit tests only\n");

    printf("%d checks, %d failures\n", checks, failures);
    return failures == 0 ? 0 : 1;
}
